name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      # Step 1: Check out the repository's code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Install the Rust toolchain and build tools
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - name: Install wasm-bindgen-cli
        run: |
          cargo install wasm-bindgen-cli

      # Step 3: Set up Node.js and pnpm
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # Point to the official npm registry
          registry-url: 'https://registry.npmjs.org'

      # Step 4: Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Step 5: Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Step 6: Build all packages
      - name: Build packages
        run: pnpm -r build

      # Step 7: Test all packages
      - name: Test packages
        run: pnpm test

      # Step 8: Create and publish a changeset
      - name: Bump version and create changelog
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm changeset version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup .npmrc file for publishing
        if: steps.changesets.outputs.published == 'true'
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: Publish to npm
        if: steps.changesets.outputs.published == 'true'
        run: pnpm --filter wasm-forge publish --access public --no-git-checks

      - name: Delete .npmrc file
        if: always() && steps.changesets.outputs.published == 'true'
        run: rm .npmrc
