name: Publish to npm

# This key makes the workflow triggerable manually from the GitHub UI.
on:
  workflow_dispatch:

  # This adds the new trigger for Git tags
  push:
    tags:
      - 'v*' # e.g., v1.0.0, v0.2.1, etc.

jobs:
  publish-packages:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository's code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install the Rust toolchain and build tools
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - name: Install wasm-bindgen-cli
        run: |
          cargo install wasm-bindgen-cli

      # Step 3: Set up Node.js and pnpm
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # Point to the official npm registry
          registry-url: 'https://registry.npmjs.org'

      # Step 4: Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Step 5: Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Step 6: Build all packages
      - name: Build packages
        run: pnpm -r build

      # Step 7: Test all packages
      - name: Test packages
        run: pnpm test

      # Step 8: Publish wasm-forge
      - name: Publish wasm-forge
        run: npm publish --access public ./packages/wasm-forge
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
